Label Enconding

label enconding and categorical encoding are two techniques used to ecode categorical data as numerical data

# label encoding involves assining a unique numerical label to each category in the variable.

# labels are assigned in alphabetical order or based on the frequency of the categories

# categorical variables are:
1. Red : 1
2. Blue : 2
3. Green : 3  
# ass unique values

In [1]:
import pandas as pd

In [14]:
df = pd.DataFrame({
    'color': ['red','green', 'blue', 'green', 'red']
})
df.head()

   color
0    red
1  green
2   blue
3  green
4    red

In [15]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [16]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\PRACHI\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 1, 0, 1, 2])

In [18]:
lbl_encoder.transform([['red']])

c:\Users\PRACHI\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [19]:
lbl_encoder.transform([['blue']])

c:\Users\PRACHI\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [20]:
lbl_encoder.transform([['green']])

c:\Users\PRACHI\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])


Label Encoding (problem for nominal data)

It assigns numbers:

Red → 3
Blue → 2
Green → 1

Now ML model may think:

Red > Blue > Green ❌ (fake order created)

Even though colors have no order

# thats why we use now ordinal encoding

Ordinal Encoding 

# tech assign numerical value based on its position in the order 
# categorical data have ranking 

# categorical variable with education level

1. High school : 1
2. College : 2 
3. Graduate : 3
4. post Graduate : 4


# it have ranks are impt

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
df = pd.DataFrame({
    'size' : ['small', 'medium', 'large', 'medium', 'small', 'large']
})
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [23]:
## assigns ranking of each : create instance of ordinalencoder 
# and then fit_trnasform
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [ ]:
encoder.fit_transform(df[['size']])  # so here gives rank small 0 , medium 1, large 2

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])